### PR TITLE
Adding feature documentation for #77

### PR DESCRIPTION
**Pull request by blasterpal**

### CODE REVIEW

**Comment by blakechambers** [comment]
I think this needs a little clarity on some things:

- POST should return a 201 status code.
- It's hard to understand the conditions of 404 on relationships requests. I'm sure there are some cases.
- [see this.](https://github.com/blakechambers/matterhorn/pull/84/files#diff-48029a9309d2459611eb90329710d5e9R70)  this doesn't seem actionable, which one should be picked here (or both)?

**Comment by blasterpal** [comment]
Regarding #1 above, the spec is clear that a 204 should be used. 

From http://jsonapi.org/format/#crud-updating-to-many-relationships starting within POST paragraphs. 

"If all of the specified resources can be added to, or are already present in, the relationship then the server MUST return a successful 204 No Content response.

Note: This approach ensures that a request is successful if the server's state matches the requested state, and helps avoid pointless race conditions caused by multiple clients making the same changes to a relationship."

**Comment by blasterpal** [comment]
Regarding #2: 
For `GET` the spec is specific on 404. For other actions, a 404 is not prevented and allowed: http://jsonapi.org/format/#crud-updating-relationship-responses-other

Regarding #3: The spec is very specific here. 

> If the client makes a DELETE request to a relationship URL, the server MUST delete the specified members from the relationship or return a 403 Forbidden response. If all of the specified resources are able to be removed from, or are already missing from, the relationship then the server MUST return a successful 204 No Content response.

**Comment by blakechambers** [comment]
this is merged as https://github.com/blakechambers/matterhorn/commit/0cbd22d1d3cd7d0107c90bc232b6c43123708ca9

**Pull request closed without merging**
